### ISSUE TITLE
Review translation of auxiliary files

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/git-novice-es#17]
Review the translations of the auxiliary files:

- [x] [CONTRIBUTING.md](https://github.com/swcarpentry/git-novice-es/blob/gh-pages/CONTRIBUTING.md)
- [x] [README.md](https://github.com/swcarpentry/git-novice-es/blob/gh-pages/README.md)
- [x] [index.md](https://github.com/swcarpentry/git-novice-es/blob/gh-pages/index.md)
- [x] [reference.md](https://github.com/swcarpentry/git-novice-es/blob/gh-pages/reference.md)
- [x] [setup.md](https://github.com/swcarpentry/git-novice-es/blob/gh-pages/setup.md)

Deadline: 2018-03-05

**Comment by orchid00** [comment]
I've assigned all the translators one episode, so we are in need of a few more volunteers.

**Comment by orchid00** [comment]
Sent a PR for CONDUCT.md
@fmichonneau  is there a way to copy this across to the other lessons, it seems to be the same COC?

**Comment by ErinBecker** [comment]
CONDUCT.md and LICENSE.md are included in [styles-es](https://github.com/swcarpentry/styles-es) and therefore don't need to be translated in the individual repos. I will remove these two files from the list above.

**Comment by fmichonneau** [comment]
Thanks @ErinBecker 
Yes, please check the translations of these files in the styles-es repo. If changes need to be brought in here, let me know and I'll update the lesson repositories.

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/git-novice-es/pull/19
