### ISSUE TITLE
bring in latest style

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/git-novice-es#2]
recent changes to the style repo fix links, especially the "contact" at the bottom. They need to be brought in here.

**Comment by orchid00** [comment]
Comment: these new files will also need translation, could you please make a list @fmichonneau ?

**Comment by fmichonneau** [comment]
no it shouldn't be necessary. The changed files have to do with the infrastructure of the template, all the translations remain in place, and no additional translation should be needed. It just fixes a few bugs with the template including syntax highlighting and broken links.

**Comment by orchid00** [comment]
what about this:  bin/lesson_initialize.py
I'm not sure if because it is in bin it won't be rendered
ref https://github.com/swcarpentry/git-novice-es/pull/18/files

**Comment by fmichonneau** [comment]
This is a script that can be used to create all the files needed when starting a new repository. I don't think it needs to be translated, as it is internal to the organization of  the repository and won't be displayed on the website.
