### ISSUE TITLE
update maintainers

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/git-novice-es#36]
I believe we should update the maintainer's page to reflect the names of the people who lead the translation effort or who will maintain the lessons.

**Comment by ErinBecker** [comment]
@raynamharris - I believe we don't yet have a Maintainer lined up for this lesson. Do you have a candidate?

**Comment by raynamharris** [comment]
I have two people in mind, but it will June before they can do instructor training. I would be happy to do it in the interim.

**Comment by ErinBecker** [comment]
Great! Can you please add yourself through a PR?

**Comment by raynamharris** [comment]
Perhaps @agbeltran would be interesting in helping, either in the interim or full time.

**Comment by ErinBecker** [comment]
@agbeltran is considering serving as the Translation Coordinator.

**Comment by raynamharris** [comment]
Awe. She will be excellent!

**Comment by raynamharris** [comment]
closed by PR https://github.com/swcarpentry/git-novice-es/pull/43
