### ISSUE TITLE
titulo?

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/git-novice-es#52]
Debe ser "El Control de Versiones" o "Control de Versiones". Elige uno.

[![](https://api.gh-polls.com/poll/01C9MDVW896GE692EJSPK62Y2A/Control%20de%20Versiones%20con%20Git)](https://api.gh-polls.com/poll/01C9MDVW896GE692EJSPK62Y2A/Control%20de%20Versiones%20con%20Git/vote)
[![](https://api.gh-polls.com/poll/01C9MDVW896GE692EJSPK62Y2A/El%20Control%20de%20Versiones%20con%20Git)](https://api.gh-polls.com/poll/01C9MDVW896GE692EJSPK62Y2A/El%20Control%20de%20Versiones%20con%20Git/vote)

**Comment by orchid00** [comment]
Can we update and close?
